import dotenv from "dotenv";
dotenv.config();
const {
  PORT,
  DATABASE,
  JWT_SECRET,
  Client_ID,
  Client_secret,
  BACKEND_URL,
  FRONTEND_URL,
  FRONTEND_LOCAL_URL,
  BACKEND_LOCAL_URL,
  PITCH_TOOL_URL,
  PITCH_TOOL_URL_LOCAL,
  STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY,
  PAYPAL_CLIENT_ID,
  PAYPAL_SECRET_ID,
  PAYPAL_API,
} = process.env;

export default {
  PRODUCTION_PORT: PORT,
  DATABASE,
  JWT_SECRET,
  Client_ID,
  Client_secret,
  FRONTEND_URL,
  BACKEND_URL,
  FRONTEND_LOCAL_URL,
  BACKEND_LOCAL_URL,
  PITCH_TOOL_URL,
  PITCH_TOOL_URL_LOCAL,
  STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY,
  PAYPAL_CLIENT_ID,
  PAYPAL_SECRET_ID,
  PAYPAL_API,
};
