export const genres = [
  { id: 4, name: "EDM", category: "Dance" },
  { id: 5, name: "Chill", category: "Dance" },
  { id: 6, name: "Future Bass", category: "Dance" },
  { id: 7, name: "Hip Hop", category: "Hip-hop & Rap" },
  { id: 8, name: "House", category: "Dance" },
  { id: 10, name: "Pop", category: "Pop" },
  { id: 11, name: "RnB", category: "RnB & Soul" },
  { id: 12, name: "Classic Rock", category: "Alternative & Indie" },
  { id: 34, name: "Blues", category: "RnB & Soul" },
  { id: 35, name: "Country", category: "Alternative & Indie" },
  { id: 36, name: "Folk", category: "Alternative & Indie" },
  { id: 37, name: "Jazz", category: "Jazz & Classical" },
  { id: 38, name: "Indie Electro", category: "Alternative & Indie" },
  { id: 39, name: "Metal", category: "Metal & Punk" },
  { id: 40, name: "Punk", category: "Metal & Punk" },
  { id: 41, name: "Soul", category: "RnB & Soul" },
  { id: 42, name: "Autotune", category: "Hip-hop & Rap" },
  { id: 43, name: "Chill-hop", category: "Hip-hop & Rap" },
  { id: 44, name: "Lo-fi", category: "Hip-hop & Rap" },
  { id: 45, name: "Rap", category: "Hip-hop & Rap" },
  { id: 46, name: "Bass House", category: "Dance" },
  { id: 47, name: "Chillstep", category: "Dance" },
  { id: 48, name: "Deep House", category: "Dance" },
  { id: 49, name: "Downtempo", category: "Electronic" },
  { id: 50, name: "Drum and Bass", category: "Dance" },
  { id: 51, name: "Dubstep", category: "Dance" },
  { id: 52, name: "Progressive House", category: "Dance" },
  { id: 53, name: "Techno", category: "Dance" },
  { id: 54, name: "Trance", category: "Dance" },
  { id: 55, name: "Tropical House", category: "Dance" },
  { id: 56, name: "Acoustic Pop", category: "Pop" },
  { id: 57, name: "Bedroom Pop", category: "Pop" },
  { id: 59, name: "Electro Pop", category: "Pop" },
  { id: 60, name: "Ambient", category: "Electronic" },
  { id: 62, name: "Hip-Hop (Instrumental)", category: "Hip-hop & Rap" },
  { id: 64, name: "Lo-Fi (Instrumental)", category: "Hip-hop & Rap" },
  { id: 65, name: "Reggae", category: "Other" },
  { id: 66, name: "Trip Hop", category: "Electronic" },
  { id: 67, name: "Gospel", category: "RnB & Soul" },
  { id: 68, name: "Indie Rock", category: "Alternative & Indie" },
  { id: 69, name: "Alt Rock", category: "Alternative & Indie" },
  { id: 70, name: "Pop Rock", category: "Alternative & Indie" },
  { id: 71, name: "Post Hardcore", category: "Metal & Punk" },
  { id: 72, name: "Hardcore", category: "Metal & Punk" },
  { id: 73, name: "Grunge", category: "Alternative & Indie" },
  { id: 74, name: "Garage Rock", category: "Alternative & Indie" },
  { id: 75, name: "Synth Wave", category: "Alternative & Indie" },
  { id: 76, name: "Grime", category: "Hip-hop & Rap" },
  { id: 77, name: "Drill", category: "Hip-hop & Rap" },
  { id: 78, name: "Deutschrap", category: "Hip-hop & Rap" },
  { id: 79, name: "Emo Hip-hop", category: "Hip-hop & Rap" },
  { id: 80, name: "Tech House", category: "Dance" },
  { id: 81, name: "Experimental", category: "Electronic" },
  { id: 82, name: "Minimal Techno", category: "Dance" },
  { id: 83, name: "Melodic Techno", category: "Dance" },
  { id: 84, name: "Breakbeat", category: "Dance" },
  { id: 85, name: "Reggaeton", category: "Latin" },
  { id: 86, name: "Afrobeat", category: "Pop" },
  { id: 87, name: "Hyperpop", category: "Pop" },
  { id: 88, name: "Neo Soul", category: "RnB & Soul" },
  { id: 89, name: "Indie RnB", category: "RnB & Soul" },
  { id: 90, name: "Classical", category: "Jazz & Classical" },
  { id: 91, name: "Instrumental", category: "Other" },
  { id: 92, name: "Neo-Classical", category: "Jazz & Classical" },
  { id: 93, name: "Cinematic", category: "Jazz & Classical" },
  { id: 94, name: "Classical Crossover", category: "Jazz & Classical" },
  { id: 95, name: "Vocal Jazz", category: "Jazz & Classical" },
  { id: 96, name: "Celtic", category: "Other" },
  { id: 98, name: "Dark Wave", category: "Alternative & Indie" },
  { id: 99, name: "Synth Pop", category: "Alternative & Indie" },
  { id: 100, name: "Italo Disco", category: "Dance" },
  { id: 101, name: "Disco", category: "Dance" },
  { id: 103, name: "Christian", category: "Other" },
  { id: 110, name: "Pop Punk", category: "Metal & Punk" },
  { id: 111, name: "Punk Rap", category: "Hip-hop & Rap" },
  { id: 112, name: "Big Beat", category: "Dance" },
  { id: 113, name: "K Pop", category: "Pop" },
  {
    id: 114,
    name: "Singer - Songwriter",
    category: "Alternative & Indie",
  },
  { id: 115, name: "Old School", category: "Hip-hop & Rap" },
  { id: 116, name: "Boombap", category: "Hip-hop & Rap" },
  { id: 118, name: "Black Metal", category: "Metal & Punk" },
  { id: 119, name: "Psychedelic", category: "Alternative & Indie" },
  { id: 120, name: "Prog", category: "Metal & Punk" },
  { id: 121, name: "Indie Pop", category: "Alternative & Indie" },
  { id: 123, name: "Indietronica", category: "Alternative & Indie" },
  { id: 124, name: "Math Rock", category: "Alternative & Indie" },
  { id: 125, name: "Post Punk", category: "Alternative & Indie" },
  { id: 126, name: "Djent", category: "Metal & Punk" },
  { id: 127, name: "Emo", category: "Metal & Punk" },
  { id: 128, name: "Art Rock", category: "Alternative & Indie" },
  { id: 129, name: "Rock n Roll", category: "Alternative & Indie" },
  { id: 130, name: "Rockabilly", category: "Alternative & Indie" },
  { id: 131, name: "Electronic Rock", category: "Alternative & Indie" },
  { id: 132, name: "Noise", category: "Metal & Punk" },
  { id: 133, name: "Metalcore", category: "Metal & Punk" },
  { id: 134, name: "Nu Metal", category: "Metal & Punk" },
  { id: 135, name: "Shoegaze", category: "Alternative & Indie" },
  { id: 136, name: "Ska", category: "Metal & Punk" },
  { id: 138, name: "Trap", category: "Hip-hop & Rap" },
  { id: 139, name: "Jungle", category: "Dance" },
  { id: 140, name: "IDM", category: "Electronic" },
  { id: 141, name: "Ac", category: "Dance" },
  { id: 144, name: "Bounce", category: "Dance" },
  { id: 145, name: "Nightcore", category: "Dance" },
  { id: 146, name: "Psytrance", category: "Dance" },
  { id: 147, name: "Hardstyle", category: "Dance" },
  { id: 149, name: "Electronica", category: "Electronic" },
  { id: 150, name: "Footwork", category: "Dance" },
  { id: 152, name: "Lounge", category: "Dance" },
  { id: 153, name: "Dub", category: "Dance" },
  { id: 154, name: "Slap House", category: "Dance" },
  { id: 155, name: "Jersey Club", category: "Dance" },
  { id: 157, name: "UK Garage", category: "Dance" },
  { id: 158, name: "Phonk", category: "Dance" },
  { id: 159, name: "Brazilian Phonk", category: "Dance" },
  { id: 160, name: "Happy Hardcore", category: "Dance" },
  { id: 161, name: "J Pop", category: "Pop" },
  { id: 162, name: "Latin (Instrumental)", category: "Latin" },
  { id: 163, name: "A Cappella", category: "Other" },
  { id: 165, name: "Avant-Garde", category: "Other" },
  { id: 166, name: "Musical", category: "Other" },
  { id: 167, name: "Dancehall", category: "Other" },
  { id: 168, name: "Soundtrack", category: "Other" },
  { id: 169, name: "Funk", category: "RnB & Soul" },
  { id: 170, name: "Opera", category: "Jazz & Classical" },
  { id: 171, name: "Swing", category: "Jazz & Classical" },
  { id: 172, name: "Folk Punk", category: "Alternative & Indie" },
  { id: 173, name: "Minimal House", category: "Dance" },
  { id: 174, name: "Chicago House", category: "Dance" },
  { id: 175, name: "Indie Folk", category: "Alternative & Indie" },
  { id: 176, name: "Lofi-Rock", category: "Alternative & Indie" },
  { id: 177, name: "Surf", category: "Alternative & Indie" },
  { id: 178, name: "Acoustic Folk", category: "Alternative & Indie" },
  { id: 179, name: "Post Rock", category: "Alternative & Indie" },
  { id: 180, name: "Dream Pop", category: "Alternative & Indie" },
  { id: 181, name: "Alt Pop", category: "Alternative & Indie" },
  { id: 182, name: "Melodic House", category: "Dance" },
  { id: 183, name: "Glitch Hop", category: "Dance" },
  { id: 184, name: "Popular Remix", category: "Dance" },
  { id: 185, name: "Bigroom", category: "Dance" },
  { id: 186, name: "Glitch", category: "Electronic" },
  { id: 187, name: "UK Hip Hop", category: "Hip-hop & Rap" },
  { id: 188, name: "Gangster Rap", category: "Hip-hop & Rap" },
  { id: 189, name: "Jazz-hop", category: "Hip-hop & Rap" },
  { id: 190, name: "Drone", category: "Electronic" },
  { id: 191, name: "Country Rap", category: "Hip-hop & Rap" },
  { id: 192, name: "Bossa Nova", category: "Jazz & Classical" },
  { id: 193, name: "Fusion", category: "Jazz & Classical" },
  { id: 194, name: "Latin Pop", category: "Latin" },
  { id: 195, name: "Bachata", category: "Latin" },
  { id: 196, name: "Cumbia", category: "Latin" },
  { id: 197, name: "Salsa", category: "Latin" },
  { id: 198, name: "Latin House", category: "Latin" },
  { id: 199, name: "Latin Rock", category: "Latin" },
  { id: 200, name: "Flamenco", category: "Latin" },
  { id: 201, name: "Deathcore", category: "Metal & Punk" },
  { id: 202, name: "Doom", category: "Metal & Punk" },
  { id: 203, name: "Thrash", category: "Metal & Punk" },
  { id: 204, name: "Stoner", category: "Metal & Punk" },
  { id: 205, name: "Hard Rock", category: "Metal & Punk" },
  { id: 206, name: "Adult Contemporary", category: "Pop" },
  { id: 207, name: "Dance Pop", category: "Pop" },
  { id: 208, name: "Afro-pop", category: "Pop" },
  { id: 209, name: "Bedroom RnB", category: "RnB & Soul" },
];
